export default {
  En: {
    LandingPage: {
      movie_quotes: "Movie Quotes",
      sign_up: "Sign up",
      log_in: "Log in",
      find_any_quote_in: "Find any quote in",
      millions_of_movie_lines: "Millions of movie lines",
      you_have_to_leave_something: "You have to leave something",
      behind_to_go_forward: "behind to go forward",
      interstellar: "Interstellar",
      i_think_we_re_just_gonna_have: "I think we're just gonna have",
      to_be_secretly_in_love_with_each_other:
        "to be secretly in love with each other",
      and_leave_it_that: "and leave it that",
      to_be_secretly_in_love: "to be secretly in love",
      with_each_other: "with each other",
      the_royal_tenenbaums: "The Royal Tenenbaums",
      I_see_in_your_eyes_the_same: "I see your eyes the same",
      fear_that_would_take_the: "fear that would take the",
      heart_of_me: "heart of me",
      the_lord_of_the_rings: "The Lord of the Rings",
      all_rights_reserved: "ALL RIGHTS RESERVED",
      get_started: "Get started",
    },
    RegistrationForm: {
      create_an_account: "Create an account",
      start_journey: "Start your journey!",
      username_taken: "The username has already been taken",
      name: "Name",
      email: "Email",
      email_taken: "The email has already been taken",
      password: "Password",
      confirm_password: "Confirm Password",
      sign_up_with_google: "Sign up with google",
      already_have_an_account: "Already have an account?",
      sign_up: "Sign up",
      log_in: "Log in",
      username_placeholder: "At least 3 & max.15 lower case characters",
      email_placeholder: "Enter your email",
      password_placeholder: "At least 8 & max.15 lower case characters",
      confirm_placeholder: "Confirm password",
    },
    LoginForm: {
      log_in_your_account: "Log in to your account",
      welcome_back: "Welcome back! Please enter your details",
      email: "Email",
      password: "Password",
      remember_me: "Remember me",
      forgot_password: "Forgot Password",
      sign_in: "Sign in",
      sign_in_google: "Sign in with Google",
      no_account: "Don't have an account?",
      sign_up: "Sign up",
      email_placeholder: "Enter your email",
      password_placeholder: "Password",
    },
    NewsFeed: {
      movie_quotes: "Movie Quotes",
      log_out: "Log out",
      edit_profile: "Edit your profile",
      list_of_movies: "List of movies",
      news_feed: "News Feed",
      enter_movies: "Enter @ to search for movies",
      enter_quotes: "Enter # to search for quotes",
      write_new_quote: "Write new quote",
      write_comment: "Write a comment",
      search: "Enter @ to search movies, Enter # to search quotes",
    },
    MovieList: {
      my_list_of_movies: "My list of movies",
      total: "Total",
      search: "Search",
      add_movie: "Add movie",
    },
  },
};
