export default {
  Ka: {
    LandingPage: {
      movie_quotes: "ფილმის ციტატები",
      sign_up: "რეგისტრაცია",
      log_in: "შესვლა",
      find_any_quote_in: "იპოვე ნებისმიერი ციტატა",
      millions_of_movie_lines: "მილიონობით ფილმიდან",
      you_have_to_leave_something: "რაღაც უნდა დატოვო",
      behind_to_go_forward: "უკან წინ წასასვლელად",
      interstellar: "ინტერსტელარი",
      i_think_we_re_just_gonna_have: "ვფიქრობ, ჩვენ უბრალოდ მოგვიწევს",
      to_be_secretly_in_love_with_each_other: "ფარულად ვიყოთ შეყვარებულები ",
      and_leave_it_that: "და ესე დავტოვოთ",
      to_be_secretly_in_love: "ფარულად ვიყოთ შეყვარებულები",

      the_royal_tenenbaums: "ტენენბაუმების ოჯახი",
      I_see_in_your_eyes_the_same: "შენ თვალებში ვხედავ იმავე შიშს",
      fear_that_would_take_the: "რომელიც წაიღებს",
      heart_of_me: "ჩემს გულს",
      the_lord_of_the_rings: "ბეჭდების მბრძანებელი",
      all_rights_reserved: "ყველა უფლება დაცულია",
      get_started: "დაწყება",
    },
    RegistrationForm: {
      create_an_account: "შექმენი ანგარიში",
      start_journey: "დაიწყე თავგადასავალი!",
      username_taken: "სახელი დაკავებულია",
      name: "სახელი",
      email: "იმეილი",
      email_taken: "იმეილი დაკავებულია",
      password: "პაროლი",
      confirm_password: "დაადასტურეთ პაროლი",
      sign_up_with_google: "დარეგისტრირდით გუგლით",
      already_have_an_account: "უკვე გაქვთ ანგარიში?",
      sign_up: "რეგისტრაცია",
      log_in: "შესვლა",
      username_placeholder: "სახელი",
      email_placeholder: "ელ-ფოსტის მისამართი",
      password_placeholder: "პაროლი",
      confirm_placeholder: "დაადასტურეთ პაროლი",
    },
    LoginForm: {
      log_in_your_account: "ანგარიშზე შესვლა",
      welcome_back: "კეთილი იყოს თქვენი დაბრუნება!",
      email: "იმეილი",
      password: "პაროლი",
      remember_me: "დამახსოვრება",
      forgot_password: "პაროლი დამავიწყდა",
      sign_in: "შესვლა",
      sign_in_google: "გუგლის ანგარიშით შესვლა",
      no_account: "არ გაქვს ანგარიში?",
      sign_up: "რეგისტრაცია",
      password_placeholder: "პაროლი",
      email_placeholder: "შეიყვანეთ იმეილი",
    },
    NewsFeed: {
      movie_quotes: "ფილმის ციტატები",
      log_out: "გასვლა",
      edit_profile: "პროფილის რედაქტირება",
      list_of_movies: "ჩემი ფილმები",
      news_feed: "ნიუს ფიდი",
      enter_movies: "ჩაწერე @ ფილმის მოსაძებნად",
      enter_quotes: "ჩაწერე # ციტატის მოსაძებნად",
      write_new_quote: "შექმენი პოსტი",
      write_comment: "დაწერე კომენტარი...",
      search: "ჩაწერე @ ფილმის მოსაძებნად, ჩაწერე # ციტატის მოძაძებნად",
    },
  },
};
