export default {
  Ka: {
    landing_page: {
      movie_quotes: "ფილმის ციტატები",
      sign_up: "რეგისტრაცია",
      log_in: "შესვლა",
      find_any_quote_in: "იპოვე ნებისმიერი ციტატა",
      millions_of_movie_lines: "მილიონობით ფილმიდან",
      you_have_to_leave_something: "რაღაც უნდა დატოვო",
      behind_to_go_forward: "უკან წინ წასასვლელად",
      interstellar: "ინტერსტელარი",
      i_think_we_re_just_gonna_have: "ვფიქრობ, ჩვენ უბრალოდ მოგვიწევს",
      to_be_secretly_in_love_with_each_other: "ფარულად ვიყოთ შეყვარებულები ",
      and_leave_it_that: "და ესე დავტოვოთ",
      to_be_secretly_in_love: "ფარულად ვიყოთ შეყვარებულები",
      the_royal_tenenbaums: "ტენენბაუმების ოჯახი",
      I_see_in_your_eyes_the_same: "შენ თვალებში ვხედავ იმავე შიშს",
      fear_that_would_take_the: "რომელიც წაიღებს",
      heart_of_me: "ჩემს გულს",
      the_lord_of_the_rings: "ბეჭდების მბრძანებელი",
      all_rights_reserved: "ყველა უფლება დაცულია",
      get_started: "დაწყება",
    },
    registration_form: {
      create_an_account: "შექმენი ანგარიში",
      start_journey: "დაიწყე თავგადასავალი!",
      username_taken: "სახელი დაკავებულია",
      name: "სახელი",
      email: "იმეილი",
      email_taken: "იმეილი დაკავებულია",
      password: "პაროლი",
      confirm_password: "დაადასტურეთ პაროლი",
      sign_up_with_google: "დარეგისტრირდით გუგლით",
      already_have_an_account: "უკვე გაქვთ ანგარიში?",
      sign_up: "რეგისტრაცია",
      log_in: "შესვლა",
      username_placeholder: "სახელი",
      email_placeholder: "ელ-ფოსტის მისამართი",
      password_placeholder: "პაროლი",
      confirm_placeholder: "დაადასტურეთ პაროლი",
    },
    login_form: {
      log_in_your_account: "ანგარიშზე შესვლა",
      welcome_back: "კეთილი იყოს თქვენი დაბრუნება!",
      email: "იმეილი",
      password: "პაროლი",
      remember_me: "დამახსოვრება",
      forgot_password: "პაროლი დამავიწყდა",
      sign_in: "შესვლა",
      sign_in_google: "გუგლის ანგარიშით შესვლა",
      no_account: "არ გაქვს ანგარიში?",
      sign_up: "რეგისტრაცია",
      password_placeholder: "პაროლი",
      email_placeholder: "შეიყვანეთ იმეილი",
      wrong_email_or_password: "არასწორი იმეილი ან პაროლი",
      email_not_verified: "მეილი არ არის ვალიდური",
      forgot_password_question: "დაგავიწყდა პაროლი?",
      instructions:
        "შეიყვანე მეილი და გამოგიგზავნით პაროლის აღდგენის ინსტრუქციას",
      send_instructions: "გამოგზავნა",
      invalid_email: "არასწორი მეილი",
      back_to_login: "უკან დაბრუნება",
      skip: "გამოტოვება",
      go_to_my_email: "მეილზე გადასვლა",
      we_have_sent_password_recovery:
        "მეილზე გამოგიგზავნეთ პაროლის აღდგენის ინსტრუქცია",
      check_your_email: "შეამოწმეთ თქვენი მეილი",
      reset_password: "პაროლის აღდგენა",
      password_must_be_different:
        "ახალი პაროლი უნდა განსხვავდებოდეს ძველი პაროლისგან",
      create_new_password: "შექმენი ახალი პაროლი",
      go_to_news_feed: "ნიუს ფიდზე გადასვლა",
      password_changed: "პაროლი წარმატებით განახლდა",
      success: "წარმატება!",
      please_check: "გთხოვთ, შეამოწმოთ მეილი",
      activate_account:
        "გთხოვთ, შეამოწმეთ მეილი და მიყევით მეილის ვალიდაციის ინსტრუქციას",
      thank_you: "გმადლობთ!",
      account_activated: "ანგარიში გააქტიურებულია!",
    },
    news_feed: {
      movie_quotes: "ფილმის ციტატები",
      log_out: "გასვლა",
      edit_profile: "პროფილის რედაქტირება",
      list_of_movies: "ჩემი ფილმები",
      news_feed: "ნიუს ფიდი",
      enter_movies: "ჩაწერე @ ფილმის მოსაძებნად",
      enter_quotes: "ჩაწერე # ციტატის მოსაძებნად",
      write_new_quote: "დაწერე პოსტი",
      write_comment: "დაწერე კომენტარი...",
      search: "ჩაწერე @ ფილმის მოსაძებნად, ჩაწერე # ციტატის მოძაძებნად",
      post: "დაპოსტვა",
    },
    movie_list: {
      my_list_of_movies: "ჩემი ფილმების სია",
      total: "ჯამში",
      quotes: "ციტატები",
      search: "მოძებნა",
      add_movie: "დამატება",
      movie_description: "ფილმის აღწერა",
      budget: "შემოსავალი",
      director: "რეჟისორი",
      add_quote: "დამატება",
      edit_quote: "ციტატის რედაქტირება",
      save_changes: "შენახვა",
      edit_movie: "ფილმის რედაქტირება",
      genre: "ჟანრი",
      view_quote: "ციტატის ნახვა",
      year: "წელი",
      edit: "შეცვლა",
      delete: "წაშლა",
    },
    profile: {
      my_profile: "ჩემი პროფილი",
      upload_new_photo: "ატვირთე ახალი ფოტო",
      edit: "შეცვლა",
      username: "სახელი",
      add: "დამატება",
      not_verified: "არავერიფიცირებული",
      email: "მეილი",
      primary_email: "მთავარი იმეილი",
      add_new_email: "იმეილის დამატება",
      password: "პაროლი",
      remove: "წაშლა",
      make_this_primary: "გახადე მთავარი",
      enter_new_username: "შეიყვანე ახალი სახელი",
      enter_new_email: "შეიყვანე ახალი მეილი",
      are_you_sure_to_make_changes: "დარწმუნებული ხართ ცვლილებებში?",
      confirm: "დადასტურება",
      cancel: "გაუქმება",
      password_should_contain: "პაროლი უნდა შეიცავდეს",
      eight_or_more_characters: "8 ზე მეტ სიმბოლოს",
      fifteen_or_more_characters: "15 დაბალი რეგისტრის სიმბოლოს",
      please_verify_new_email_address: "გთხოვთ დაადასტუროთ ახალი მეილი",
    },
    notification: {
      notifications: "შეტყობინებები",
      no_notifications_yet: "ცარიელია",
      mark_as_all_read: "მონიშნე წაკითხულად",
      commented_to_your_movie_quote: "დატოვა კომენტარი შენს პოსტზე",
      reacted_to_your_quote: "დაგილაიქა ციტატა",
      new: "ახალი",
    },
  },
};
